variable "aws_region" {
  description = "AWS region where staging resources are created."
  type        = string
}

variable "project_name" {
  description = "Project name used in resource names and tags."
  type        = string
}

variable "environment" {
  description = "Deployment environment name."
  type        = string
}

variable "vpc_cidr" {
  description = "IPv4 CIDR block for the staging VPC."
  type        = string
}

variable "availability_zones" {
  description = "Two availability zones used by staging."
  type        = list(string)
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for the public subnets."
  type        = list(string)
}

variable "private_subnet_cidrs" {
  description = "CIDR blocks for the private subnets."
  type        = list(string)
}
variable "container_port" {
  description = "Port the application container listens on."
  type        = number
  default     = 8080
}

variable "health_check_path" {
  description = "Path the load balancer probes for container health."
  type        = string
  default     = "/health"
}

variable "image_tag" {
  description = "Tag of the image in ECR that the ECS service runs."
  type        = string
}

variable "task_cpu" {
  description = "CPU units reserved for each task (1024 = 1 vCPU)."
  type        = number
  default     = 256
}

variable "task_memory" {
  description = "Memory in MiB reserved for each task."
  type        = number
  default     = 512
}

variable "desired_count" {
  description = "Number of tasks the ECS service keeps running."
  type        = number
  default     = 1
}

variable "log_retention_days" {
  description = "Days CloudWatch retains container logs."
  type        = number
  default     = 30
}

variable "root_domain" {
  description = "Root domain whose Route53 hosted zone holds this environment's records, e.g. charity-syria.com."
  type        = string
  default     = "charity-syria.com"
}

variable "domain_name" {
  description = "Domain this environment answers on, e.g. staging.charity-syria.com. Empty disables ACM, Route53 and the HTTPS listener, leaving the ALB on plain HTTP."
  type        = string
  default     = ""
}

variable "db_name" {
  description = "Name of the initial database created inside the instance."
  type        = string
  default     = "charityapp"
}

variable "db_master_username" {
  description = "Database master user name. The password is generated by RDS and kept in Secrets Manager."
  type        = string
  default     = "charityapp_admin"
}

variable "db_engine_version" {
  description = "PostgreSQL version. A major version alone tracks the latest minor of that major."
  type        = string
  default     = "16"
}

variable "db_parameter_group_family" {
  description = "Parameter group family, matching the major version in db_engine_version."
  type        = string
  default     = "postgres16"
}

variable "db_instance_class" {
  description = "Database instance size."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage" {
  description = "Storage in GiB provisioned at creation."
  type        = number
  default     = 20
}

variable "db_max_allocated_storage" {
  description = "Upper bound in GiB for storage autoscaling."
  type        = number
  default     = 100
}

variable "db_multi_az" {
  description = "Whether to run a standby in the second AZ."
  type        = bool
  default     = false
}

variable "db_backup_retention_period" {
  description = "Days of automated backups retained."
  type        = number
  default     = 7
}

variable "db_deletion_protection" {
  description = "Whether AWS refuses to delete the database instance."
  type        = bool
  default     = false
}

variable "db_skip_final_snapshot" {
  description = "Whether destroying the database skips the final snapshot."
  type        = bool
  default     = true
}

variable "enable_db_check" {
  description = "Whether the container serves /db-check. The endpoint is public through the ALB and reports the database hostname, name and user, so keep it off outside staging."
  type        = bool
  default     = false
}

variable "app_secret_initial_values" {
  description = "Keys the application secret is created with, and their placeholder values. Terraform writes these once at creation and never again - replace them out of band."
  type        = map(string)
  default     = {}
}

variable "secret_recovery_window_in_days" {
  description = "Days a deleted secret stays recoverable. 0 for disposable environments."
  type        = number
  default     = 7
}

variable "github_org" {
  description = "GitHub organisation or user that owns the deployment repository."
  type        = string
  default     = ""
}

variable "github_repo" {
  description = "Repository GitHub Actions deploys from. Empty disables the OIDC deploy role entirely."
  type        = string
  default     = ""
}

variable "github_org_id" {
  description = "Numeric GitHub id of the org/user, used for the immutable OIDC subject form."
  type        = string
  default     = ""
}

variable "github_repo_id" {
  description = "Numeric GitHub id of the repository, used for the immutable OIDC subject form."
  type        = string
  default     = ""
}
